### ISSUE TITLE
TODO: Use rugged (libgit2) to handle git repository

### ISSUE THREAD

**Issue by sh19910711** [sh19910711/git-contest#37]
In order to make tests faster, we should prevent shell executions (e.g. git commands). First job is to move git operation into Git class, and the next is to rewrite its methods to use rugged [1].
## TODO
- [ ] 1. Git class (in shell)
- [ ] 2. Git class (with Rugged)
- [ ] 3. Bump version into 0.3.0
## 

[1] rugged: https://github.com/libgit2/rugged
